### ISSUE TITLE
Archlinux version error

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#31]
I am using the arch version of newm, however the version is not respected when building this causes the package to always be marked as outdated

**Comment by jbuchermn** [comment]
AUR has version v0.1 - I'm not going to publish an unstable version there. As soon as all bugs are resolved and v0.2 is stable (enough), I will merge it into master and AUR version is going to be updated.

If you uninstall unstable v0.2 beforehand - does AUR installation actually fail?

**Comment by CRAG666** [comment]
It does not fail, the point to which is that the PKBUILD has a declared version, so when making makepkg -sc the resulting version is another. This causes yay or any other aur admin to mark the package as out-of-date.

**Comment by jbuchermn** [comment]
What do you suggest I change?

**Comment by CRAG666** [comment]
simply remove these lines
``` bash
pkgver() {
    cd $srcdir/newm
    git describe --tags --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}
```

**Comment by CRAG666** [comment]
``` bash
# Maintainer: oldNo.7 <oldNo.7@archlinux.org>

pkgname=catapult
pkgver=3.1
pkgrel=1
pkgdesc="App launcher for Linux, similar to ulauncher(wayland support)"
arch=('any')
url="https://github.com/otsaloma/catapult.git"
license=('GPL 3.0')
depends=('python' 'glib2' 'gtk3' 'python-gobject' 'libkeybinder3' 'gettext' 'libqalculate' 'pango')
source=("${pkgname%-git}::git+${url}")
sha256sums=('SKIP')

build() {
  cd "${srcdir}/${pkgname}"
  make build
}

package() {
  cd "${srcdir}/${pkgname}"
  make DESTDIR="${pkgdir}" PREFIX=/usr install
}
```
This is the pkbuild I made for catapult(although I still don't know how to upload it) it could be useful for you as a guide

**Comment by jbuchermn** [comment]
This is kind of in contradiction to https://wiki.archlinux.org/title/VCS_package_guidelines

I still don't understand what issues this would fix. If you don't have newm install and run
```
yay -S newm-git
```
there are no issues, nor when you later update using
```
yay -S newm-git
```

Whay would you run `makepkg -sc` in that case anyway?

**Comment by CRAG666** [comment]
Well, install newm and then do yay -Syyu and you will see how yay marks as out of date even though you just installed the package.

**Comment by jbuchermn** [comment]
Okay thanks, I will try that.

**Comment by jbuchermn** [comment]
Just tried `yay -S newm-git` and then `yay -Syyu' and didn't have any issues:

```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  newm-git-0.1-1

  1 newm-git                                 (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: PKGBUILD up to date, Skipping (1/0): newm-git
  1 newm-git                                 (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: (1/1) Parsing SRCINFO: newm-git
==> Making package: newm-git 0.1-1 (Tue 23 Nov 2021 08:10:40 AM CET)
==> Retrieving sources...
  -> Updating pywm git repo...
Fetching origin
  -> Updating newm git repo...
Fetching origin
==> Validating source files with md5sums...
    pywm ... Skipped
    newm ... Skipped
==> Making package: newm-git 0.1-1 (Tue 23 Nov 2021 08:10:41 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating pywm git repo...
Fetching origin
  -> Updating newm git repo...
Fetching origin
==> Validating source files with md5sums...
    pywm ... Skipped
    newm ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of pywm git repo...
Cloning into 'pywm'...
done.
  -> Creating working copy of newm git repo...
Cloning into 'newm'...
done.
==> Starting prepare()...
Submodule 'subprojects/wlroots' (https://github.com/swaywm/wlroots) registered for path 'subprojects/wlroots'
Cloning into '/home/jonas/.cache/yay/newm-git/src/pywm/subprojects/wlroots'...
Submodule path 'subprojects/wlroots': checked out '0467a7523ae79abd454b1fa9e7161d54d3c6f069'
==> Starting pkgver()...
==> Updated version: newm-git v0.1.r27.g33aea1f-1
==> Sources are ready.
==> Making package: newm-git v0.1.r27.g33aea1f-1 (Tue 23 Nov 2021 08:10:46 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
 -> newm-git-v0.1.r27.g33aea1f-1 already made -- skipping build
 -> Found git repo: github.com/jbuchermn/newm.git
 -> Found git repo: github.com/jbuchermn/pywm.git
loading packages...
warning: newm-git-v0.1.r27.g33aea1f-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) newm-git-v0.1.r27.g33aea1f-1

Total Installed Size:  2.36 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                                                   [##############################################################################] 100%
(1/1) checking package integrity                                                                                                 [##############################################################################] 100%
(1/1) loading package files                                                                                                      [##############################################################################] 100%
(1/1) checking for file conflicts                                                                                                [##############################################################################] 100%
(1/1) checking available disk space                                                                                              [##############################################################################] 100%
:: Processing package changes...
(1/1) reinstalling newm-git                                                                                                      [##############################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

**Comment by CRAG666** [comment]
In itself there is no problem, only that the package is always marked as outdated

**Comment by CRAG666** [comment]
This version does not correspond to the version of the package newm-git-v0.1.r27.g33aea1f-1, ![newm](https://i.ibb.co/Ss9ThX4/screen-1637677232.png)
So even when you have just installed newm it will always be marked as out of date, in the image is the execution of yay -Syyu just after installing newm and it is already marked as out of date.

**Comment by jbuchermn** [comment]
I think the issue here is that newm versions contain "v" which https://wiki.archlinux.org/title/VCS_package_guidelines forbids. I just pushed a fix to AUR - does this work for you?

**Comment by CRAG666** [comment]
I'll try it in a moment

**Comment by CRAG666** [comment]
is working
