### ISSUE TITLE
Unable switch tty

### ISSUE THREAD

**Issue by fedoranvar** [jbuchermn/newm#99]
Good day to you!
 
 i've started vanilla config in tty2 with `start-newm`
 
 But after that i can't switch to another tty
 
 Is it designed so?
 
 Thank you!

**Comment by jbuchermn** [comment]
Hey,

that's not by design but can happen when newm crashes or doesn't start up properly. Is it actually usable?

If newm runs properly, Ctrl-Alt-Fx is detected and the tty switched.

**Comment by fedoranvar** [comment]
```

**Comment by jbuchermn** [comment]
Ah I just did a test and I can reproduce. This appears to be a regression caused by recent keybinding changes. I'll take a look into fixing this

**Comment by jbuchermn** [comment]
I just pushed a fix to pywm

**Comment by fedoranvar** [comment]
i'm installing newm through flakes, (have copied from you dotfiles)

![image](https://user-images.githubusercontent.com/52028706/163217615-4deab0a2-33be-484f-8dad-440307f6391a.png)
![image](https://user-images.githubusercontent.com/52028706/163217671-76f8b890-ed6b-4d36-a41f-62af23269ba8.png)

but still can't switch tty, am i doing right?

**Comment by jbuchermn** [comment]
Ah okay, probably then you don't get the most current pywm version, but instead the one from newms flake.lock (unless you override newms input). Btw. you should not actually need to add pywm to your config (take a look at https://github.com/jbuchermn/dotfiles-nix/blob/main/flake.nix )

Anyway, I just updated newms flake.lock. So if you install the current flake version you should get the update.

**Comment by fedoranvar** [comment]
now switchiing is working.

Thank you!
